#ifndef BOARD_H
#define BOARD_H

#include "sdk/nrfduino.h"

#define PIN_LED_ADVERTISING NRFDUINO_PIN_IO0
#define PIN_LED_CONNECTED   NRFDUINO_PIN_LED
#define PIN_LED_DATA        NRFDUINO_PIN_IO1

#define PIN_LEDSTRIP0       NRFDUINO_PIN_A0
#define PIN_LEDSTRIP1       NRFDUINO_PIN_A1
#define PIN_LEDSTRIP2       NRFDUINO_PIN_A2
#define PIN_LEDSTRIP3       NRFDUINO_PIN_A3

#endif // BOARD_H
